package dev.cjson.schema.types.conversation;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;

import java.time.OffsetDateTime;

public record TextBlock(
        @Schema(description = "The unique identifier of this text block in the conversation. UUIDs/ULIDs are recommended but not enforced.")
        @NotNull String id,

        @Schema(description = "The text of the message.")
        @NotNull String text,

        @Schema(description = """
                Whether the text block is streaming or not. This is useful to signal a text block that is still in the process of
                being generated by the model via a Streaming API.
                """)
        boolean isStreaming,

        @NotNull OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) implements ContentBlock {
}