name: Build & Deploy Antora to Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g @antora/cli @antora/site-generator
      - run: antora antora-playbook.yml --stacktrace
      - run: echo "cjson.dev" > build/site/CNAME
      - uses: actions/upload-pages-artifact@v3
        with: { path: build/site }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
